apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fastapi-app.fullname" . }}
  labels:
    {{- include "fastapi-app.labels" . | nindent 4 }}
data:
  project-name: {{ .Values.config.projectName | quote }}
  version: {{ .Values.config.version | quote }}
  api-v1-str: {{ .Values.config.apiV1Str | quote }}
  postgres-host: {{ include "fastapi-app.fullname" . }}-postgresql
  postgres-port: "5432"
  postgres-db: {{ .Values.postgresql.auth.database | quote }}
  redis-host: {{ include "fastapi-app.fullname" . }}-redis-master
  redis-port: "6379"
  algorithm: {{ .Values.config.algorithm | quote }}
  access-token-expire-minutes: {{ .Values.config.accessTokenExpireMinutes | quote }}
  allowed-origins: {{ .Values.config.allowedOrigins | quote }}
  db-pool-size: {{ .Values.config.dbPoolSize | quote }}
  db-max-overflow: {{ .Values.config.dbMaxOverflow | quote }}
  db-pool-timeout: {{ .Values.config.dbPoolTimeout | quote }}
  cache-ttl: {{ .Values.config.cacheTtl | quote }}
